# Generated by Django 5.0.7 on 2025-03-22 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_title', models.CharField(max_length=200)),
                ('document_file', models.FileField(upload_to='print_documents/')),
                ('print_type', models.CharField(choices=[('bw', 'Black & White'), ('color', 'Color')], max_length=10)),
                ('print_side', models.CharField(choices=[('single', 'Single Sided'), ('double', 'Double Sided')], max_length=10)),
                ('copies', models.PositiveIntegerField(default=1)),
                ('pickup_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.vendor')),
            ],
        ),
    ]
